classpath prepending
sbt/launcher pull request #50
Opened 2018-03-09 10:07 UTC by fommil

2018-03-09 10:10 UTC, dwijnand approved these changes
I'm happy to accept this. requesting review by @eed3si9n.

2018-03-11 15:16 UTC, eed3si9n commented on launcher-implementation/src/main/scala/xsbt/boot/ModuleDefinition.scala
> +  lazy val fullClasspath: Array[File] = concat(concat(monkeys, classpath), definition.extraClasspath)
Is this meant to patch the launched application like sbt, or the Scala library?

2018-03-11 15:18 UTC, eed3si9n requested changes
More of a question.
If this is meant to patch Scala, it might not work because we use classloader to resolve them.

2018-03-11 16:09 UTC, fommil commented
this is not meant to patch scala or zinc, it is meant to patch the launched application. In this case, sbt.

For patching the scala compiler and zinc, see https://github.com/sbt/sbt/pull/3643

2018-03-27 08:42 UTC, fommil commented
@eed3si9n any more requests for this? Shame we missed the 1.1.2 release.

2018-03-28 19:53 UTC, eed3si9n approved these changes

2018-03-28 19:54 UTC, eed3si9n commented
LGTM

2018-03-28 19:54 UTC, merged