Fix j9 crash by avoiding instantiating WrappedString
sbt/launcher pull request #74
Opened 2019-08-27 20:54 UTC by eatkins

https://github.com/sbt/sbt/issues/4985 reported that sbt would
immediately crash when using the latest launcher (1.1.2). The crashes
indicated that the problems arose when jit-ing
scala/collection/immutable/WrappedString.apply. We can avoid making a
WrappedString by using `+:` instead of `++`.

Fixes https://github.com/sbt/sbt/issues/4985.

2019-08-27 21:23 UTC, eed3si9n requested changes

2019-08-27 21:23 UTC, eed3si9n commented on launcher-implementation/src/main/scala/xsbt/boot/Launch.scala
> +           |""".stripMargin +: retrievedApp.fullClasspath.toList.map(x => " * " + x.getAbsolutePath)).mkString(System.lineSeparator)
This looks like I originally typo'ed or got confused by the code behind it, but shouldn't it be just straight-up `+` to concatenate two strings?

2019-08-27 21:29 UTC, eatkins commented
Oh, yeah, that’s true `+` vs `++` would probably fix the issue. While I’m at it, do we really want the sbt issue number in the message?

2019-08-27 21:54 UTC, eed3si9n commented
> While I’m at it, do we really want the sbt issue number in the message?

Yes, I think this is a good idea, if I say so myself. The number is unique, and if people run into this issue, (which should not normally happen unless your cache is messed up) they can comment on it. I wish I could put GitHub issue reference to all error messages.

2019-08-27 22:05 UTC, eatkins commented
I'm not as enthusiastic about having issues in the error messages, but I don't mind.

```
> console
[info] Starting scala interpreter...
[info]
Welcome to Scala version 2.10.7 (OpenJDK 64-Bit Server VM, Java 1.7.0_222).
Type in expressions to have them evaluated.
Type :help for more information.

scala> "foo" + "bar"
res0: String = foobar

scala> "foo" ++ "bar"
res1: String = foobar
```

I'm not a huge fan of WrappedString being in the default scope. It leads to a lot of confusing behavior like:
```
scala> Seq("foo", "bar").flatMap(_ + "baz")
res2: Seq[Char] = List(f, o, o, b, a, z, b, a, r, b, a, z)
```
(Obviously that's a scala thing not an sbt thing).

2019-08-27 22:16 UTC, merged

2019-08-28 11:54 UTC, viktorklang commented on launcher-implementation/src/main/scala/xsbt/boot/Launch.scala
> +           |""".stripMargin +: retrievedApp.fullClasspath.toList.map(x => " * " + x.getAbsolutePath)).mkString(System.lineSeparator)
why not `.iterator.map … mkString`?

2019-08-28 13:07 UTC, eed3si9n commented on launcher-implementation/src/main/scala/xsbt/boot/Launch.scala
> +           |""".stripMargin +: retrievedApp.fullClasspath.toList.map(x => " * " + x.getAbsolutePath)).mkString(System.lineSeparator)
I guess because I prefer concrete datatype until it matters.